# Pre-seed DO instance to look like AWS and GCloud
- name: Configure ubuntu
  hosts: all
  gather_facts: no
  remote_user: root
  tasks:
  - name: 'Install python2'
    raw: sudo apt-get -y install python-simplejson

  - name: Ensure group "ubuntu" exists
    group:
      name: ubuntu
      state: present

  - name: Create new user
    user:
      name: ubuntu
      groups: sudo,ubuntu
      shell: /bin/bash

  - name: Create .ssh folder
    file:
      path: ~ubuntu/.ssh
      state: directory
      owner: ubuntu
      group: ubuntu
      mode: 0700

  - name: Upload SSH key
    copy:
      src: ~/.ssh/do.pub
      dest: ~ubuntu/.ssh/authorized_keys
      owner: ubuntu
      group: ubuntu
      mode: 0700

  - name: Allow sudo without password
    lineinfile:
      path: /etc/sudoers
      line: "ubuntu ALL=(ALL) NOPASSWD: ALL"
