---
- name: Install telegraf
  become: True
  apt:
    deb: https://dl.influxdata.com/telegraf/releases/telegraf_1.6.1-1_amd64.deb

- name: Configure telegraf
  become: True
  template:
    src: "telegraf.conf"
    dest: /etc/telegraf/telegraf.conf
    owner: root
    group: root
    mode: 0644

- name: Restart statsd
  become: True
  service: name=telegraf state=restarted