FROM golang:1.10

RUN go get github.com/ethereum/go-ethereum
RUN go get github.com/cactus/go-statsd-client/statsd
RUN go get github.com/gorilla/mux
RUN go get github.com/regcostajr/go-web3
RUN go get github.com/pubnub/go/messaging
RUN go get gopkg.in/yaml.v2

